from pathlib import Path

from sqlalchemy.orm import Session

from app import llm
from app.models import Client, Draft, DocType, DraftStatus, User
from app.security import log_action
from app.services.intake import build_client_data
from app.services.risk_flagging import check_draft

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "templates_lib"

TEMPLATE_FILES = {
    DocType.WILL: "will.txt",
    DocType.POA_FINANCIAL: "poa_financial.txt",
    DocType.POA_HEALTHCARE: "poa_healthcare.txt",
    DocType.HIPAA_AUTHORIZATION: "hipaa_authorization.txt",
}

WATERMARK_HEADER = (
    "=== DRAFT — PENDING ATTORNEY REVIEW — NOT FOR EXECUTION ===\n"
    "This document was generated by an AI drafting assistant from firm\n"
    "templates and client intake data. It is not legal advice and has no\n"
    "legal effect until reviewed, revised as needed, and approved by a\n"
    "licensed attorney.\n"
    "=============================================================\n\n"
)


def load_template(doc_type: DocType) -> str:
    return (TEMPLATES_DIR / TEMPLATE_FILES[doc_type]).read_text()


def generate_draft(db: Session, client: Client, doc_type: DocType, user: User) -> Draft:
    template_text = load_template(doc_type)
    client_data = build_client_data(client)
    body = llm.draft_document(doc_type.value, template_text, client_data)

    draft = Draft(
        client_id=client.id,
        doc_type=doc_type,
        content=WATERMARK_HEADER + body,
        status=DraftStatus.DRAFT,
        generated_by=user.id,
    )
    db.add(draft)
    db.commit()
    db.refresh(draft)

    log_action(db, user, "generate_draft", "draft", draft.id, detail=doc_type.value)
    check_draft(db, draft, user, client_data=client_data)
    return draft
